// trades/unit-prices.js — 기준단가 데이터 (년도/반기별 관리)
var UNIT_PRICES = {
  year: '2026',
  half: '상반기',
  updated: '2026-01-15',

  // 노임단가 (시중노임단가 기준)
  labor: [
    { id: 'dobae',      name: '도배공',   price: 227614, source: '시중노임단가' },
    { id: 'general',    name: '보통인부', price: 150316, source: '시중노임단가' },
    { id: 'interior',   name: '내장공',   price: 256883, source: '시중노임단가' },
    { id: 'carpenter',  name: '목공',     price: 236457, source: '시중노임단가' },
    { id: 'plasterer',  name: '미장공',   price: 230000, source: '시중노임단가' },
    { id: 'plumber',    name: '설비공',   price: 250000, source: '시중노임단가' },
    { id: 'tiler',      name: '타일공',   price: 235000, source: '시중노임단가' },
    { id: 'painter',   name: '도장공',   price: 228000, source: '시중노임단가' },
    { id: 'floor',     name: '마루공',   price: 220000, source: '시중노임단가' },
    { id: 'waterproof', name: '방수공',  price: 235000, source: '시중노임단가' },
    { id: 'electric',   name: '전기공',   price: 242000, source: '시중노임단가' },
    { id: 'insulation', name: '단열공',   price: 240000, source: '시중노임단가' },
  ],

  // 자재단가 (한국물가정보 기준)
  material: [
    { id: 'silk',       name: '실크벽지',         unit: '㎡', price: 8000,  source: '물가정보' },
    { id: 'hapji',      name: '합지벽지',         unit: '㎡', price: 6000,  source: '물가정보' },
    { id: 'chobae',     name: '초배지',           unit: '㎡', price: 1500,  source: '물가정보' },
    { id: 'glue',       name: '도배풀',           unit: 'kg', price: 3000,  source: '물가정보' },
    { id: 'sub',        name: '부자재(테이프 등)',  unit: '식', price: 30000, source: '물가정보' },
    { id: 'silicon',    name: '실리콘',           unit: '개', price: 5000,  source: '물가정보' },
    { id: 'gyp-board',  name: '석고보드 9.5mm',    unit: '매', price: 4500,  source: '물가정보' },
    { id: 'gyp-board12',name: '석고보드 12.5mm',   unit: '매', price: 5500,  source: '물가정보' },
    { id: 'gyp-putty',  name: '석고보드 퍼티',     unit: 'kg', price: 2000,  source: '물가정보' },
    { id: 'gyp-tape',   name: '조인트 테이프',     unit: 'm',  price: 300,   source: '물가정보' },
    { id: 'gyp-screw',  name: '석고보드 나사',     unit: '개', price: 30,    source: '물가정보' },
    { id: 'gyp-sub',    name: '목공 부자재',       unit: '식', price: 25000, source: '물가정보' },
    { id: 'mold-pvc',   name: '몰딩 PVC',         unit: 'm',  price: 3000,  source: '물가정보' },
    { id: 'mold-mdf',   name: '몰딩 MDF',         unit: 'm',  price: 5000,  source: '물가정보' },
    { id: 'mold-wood',  name: '몰딩 원목',         unit: 'm',  price: 8000,  source: '물가정보' },
    { id: 'base-pvc',   name: '걸레받이 PVC',      unit: 'm',  price: 2000,  source: '물가정보' },
    { id: 'base-mdf',   name: '걸레받이 MDF',      unit: 'm',  price: 3500,  source: '물가정보' },
    { id: 'cab-hinge-mat', name: '경첩 (스테인리스)', unit: '개', price: 5000,  source: '물가정보' },
    { id: 'cab-rail-mat',  name: '서랍 레일',        unit: '조', price: 8000,  source: '물가정보' },
    { id: 'cab-door-mat',  name: '싱크대 문짝',      unit: '짝', price: 45000, source: '물가정보' },
    { id: 'cab-panel',    name: '합판/MDF 패널',    unit: 'm',  price: 15000, source: '물가정보' },
    { id: 'cab-sub',      name: '부자재(본드·못)',   unit: 'm',  price: 5000,  source: '물가정보' },
    // 싱크대
    { id: 'sink-lower',   name: '싱크대 하부장',       unit: 'm',  price: 160000, source: '물가정보' },
    { id: 'sink-upper',   name: '싱크대 상부장',       unit: 'm',  price: 135000, source: '물가정보' },
    { id: 'sink-deco',    name: '장식장 (색상통일)',     unit: 'm',  price: 140000, source: '물가정보' },
    { id: 'sink-top-art', name: '상판 (인조대리석)',    unit: 'm',  price: 130000, source: '물가정보' },
    { id: 'sink-top-qtz', name: '상판 (석영석)',       unit: 'm',  price: 200000, source: '물가정보' },
    { id: 'sink-bowl',    name: '씽크볼 (스테인리스)',  unit: '대', price: 85000,  source: '물가정보' },
    { id: 'sink-bowl-uq', name: '씽크볼 (언더마운트)',  unit: '대', price: 150000, source: '물가정보' },
    { id: 'sink-drain',   name: '홈통+배수구 세트',     unit: '식', price: 25000,  source: '물가정보' },
    { id: 'sink-hose',    name: '연결 호스 (급수)',      unit: '조', price: 12000,  source: '물가정보' },
    { id: 'sink-sealant', name: '씽크볼 실리콘+고정부속', unit: '식', price: 8000, source: '물가정보' },
    { id: 'sink-faucet',  name: '수전 (싱크대용)',     unit: '대', price: 70000,  source: '물가정보' },
    { id: 'sink-pipe-s',  name: '급수 배관 부속',      unit: '식', price: 15000,  source: '물가정보' },
    { id: 'sink-pipe-d',  name: '배수 트랩+부속',      unit: '식', price: 20000,  source: '물가정보' },
    { id: 'sink-tile',    name: '타일 (벽면 보수용)',   unit: '㎡', price: 25000,  source: '물가정보' },
    { id: 'sink-adhesive', name: '타일 접착제',        unit: 'kg', price: 2000,   source: '물가정보' },
    // 바닥
    { id: 'fl-gangmaru',  name: '강마루',          unit: '㎡', price: 18000, source: '물가정보' },
    { id: 'fl-ondol',     name: '온돌마루',        unit: '㎡', price: 25000, source: '물가정보' },
    { id: 'fl-jangpan',   name: '장판',            unit: '㎡', price: 8000,  source: '물가정보' },
    { id: 'fl-tile',      name: '바닥 타일',       unit: '㎡', price: 30000, source: '물가정보' },
    { id: 'fl-leveling',  name: '셀프레벨링재',    unit: '㎡', price: 5000,  source: '물가정보' },
    { id: 'fl-baseboard', name: '걸레받이',        unit: 'm',  price: 3000,  source: '물가정보' },
    { id: 'fl-threshold', name: '문턱',            unit: '개', price: 15000, source: '물가정보' },
    // 페인트
    { id: 'pt-water',     name: '수성페인트',      unit: 'L',  price: 7000,  source: '물가정보' },
    { id: 'pt-waterproof', name: '방수페인트',     unit: 'L',  price: 12000, source: '물가정보' },
    { id: 'pt-enamel',    name: '에나멜 (유성)',   unit: 'L',  price: 10000, source: '물가정보' },
    { id: 'pt-primer',    name: '곰팡이방지 프라이머', unit: 'L', price: 15000, source: '물가정보' },
    { id: 'pt-putty',     name: '도장용 퍼티',     unit: 'kg', price: 3000,  source: '물가정보' },
    { id: 'pt-masking',   name: '마스킹 자재',     unit: '식', price: 25000, source: '물가정보' },
    // 화장실
    { id: 'bt-tile-fl',   name: '화장실 바닥타일', unit: '㎡', price: 35000, source: '물가정보' },
    { id: 'bt-tile-wall', name: '화장실 벽타일',   unit: '㎡', price: 30000, source: '물가정보' },
    { id: 'bt-grout',     name: '줄눈재',          unit: 'kg', price: 3000,  source: '물가정보' },
    { id: 'bt-waterproof', name: '바닥 방수재',    unit: '㎡', price: 15000, source: '물가정보' },
    { id: 'bt-toilet',    name: '양변기',          unit: '대', price: 220000, source: '물가정보' },
    { id: 'bt-basin',     name: '세면대+수전',     unit: '대', price: 180000, source: '물가정보' },
    { id: 'bt-dome',      name: '돔천장 (신품)',   unit: '식', price: 160000, source: '물가정보' },
    { id: 'bt-fan',       name: '환풍기',          unit: '대', price: 40000,  source: '물가정보' },
    { id: 'bt-accy',      name: '악세사리 (수건걸이 등)', unit: '식', price: 30000, source: '물가정보' },
    // 청소
    { id: 'cl-detergent', name: '세정제',          unit: '식', price: 15000, source: '물가정보' },
    { id: 'cl-disinfect', name: '살균소독 약품',   unit: '식', price: 30000, source: '물가정보' },
    { id: 'dust-sheet',   name: '분진 차단막 (비닐+테이프)', unit: '식', price: 35000, source: '물가정보' },
    { id: 'mold-treat',   name: '곰팡이 방지 약품',  unit: '식', price: 80000, source: '물가정보' },
    { id: 'caulk-silicon', name: '실리콘 코킹재',    unit: '개', price: 5000,  source: '물가정보' },
  ],

  // 표준품셈 시공량 (건설공사 표준품셈 5-3-7)
  productivity: [
    { id: 'replace-wall',    name: '도배 교체 벽면 (합지)', unit: '㎡/일', value: 46, note: '도배공 2인 기준 · 표준품셈 5-3-7' },
    { id: 'replace-wall-silk', name: '도배 교체 벽면 (실크)', unit: '㎡/일', value: 35, note: '도배공 2인 기준 · 실크 풀먹임 숙성으로 시공량 감소' },
    { id: 'replace-ceiling', name: '도배 교체 천장 (합지)', unit: '㎡/일', value: 35, note: '도배공 2인 기준 · 표준품셈 5-3-7' },
    { id: 'replace-ceiling-silk', name: '도배 교체 천장 (실크)', unit: '㎡/일', value: 27, note: '도배공 2인 기준 · 실크 풀먹임 숙성으로 시공량 감소' },
    { id: 'remove-wall',     name: '도배 해체 벽면', unit: '품/㎡', value: 0.008, note: '도배공' },
    { id: 'remove-ceiling',  name: '도배 해체 천장', unit: '품/㎡', value: 0.010, note: '도배공' },
    { id: 'protect-floor',   name: '바닥 보양',      unit: '품/㎡', value: 0.005, note: '보통인부 · 비닐+합판' },
    { id: 'protect-mat',     name: '보양 자재비',    unit: '원/㎡', value: 400,   note: '비닐+테이프 · 물가정보' },
    { id: 'furniture-move',  name: '가구 이동',      unit: '품/회', value: 1.0,   note: '보통인부 · 별도 계상' },
    { id: 'obstacle',        name: '지장물 감소율',   unit: '%',    value: 15,    note: '실거주 세대 적용' },
    { id: 'loss',            name: '자재 로스율',    unit: '%',    value: 10,    note: '표준품셈 기준' },
    // 목공 — 석고보드 (표준품셈 3-4)
    { id: 'gyp-install',     name: '석고보드 붙이기', unit: '㎡/일', value: 33,   note: '목공 1인 기준' },
    { id: 'gyp-remove',      name: '석고보드 해체',   unit: '품/㎡', value: 0.012, note: '목공' },
    { id: 'gyp-putty-work',  name: '퍼티·줄눈 처리', unit: '품/㎡', value: 0.015, note: '미장공' },
    { id: 'gyp-board-usage', name: '석고보드 소요량', unit: '매/㎡', value: 0.63,  note: '900×1800 기준' },
    { id: 'gyp-screw-usage', name: '나사 소요량',    unit: '개/㎡', value: 25,    note: '@200간격' },
    // 목공 — 몰딩 (표준품셈 5-3 수장공사)
    { id: 'mold-remove',     name: '몰딩 해체',      unit: '품/m', value: 0.02,  note: '목공' },
    { id: 'mold-install',    name: '몰딩 설치',      unit: '품/m', value: 0.04,  note: '목공' },
    // 목공 — 걸레받이 (표준품셈 5-3)
    { id: 'base-remove',     name: '걸레받이 해체',   unit: '품/m', value: 0.015, note: '목공' },
    { id: 'base-install',    name: '걸레받이 설치',   unit: '품/m', value: 0.03,  note: '목공' },
    // 목공 — 가구·상 수리 (표준품셈 5-4 가구공사)
    { id: 'cab-partial',      name: '부분 절단 재설치', unit: '품/m',    value: 1.3, note: '목공 · 절단0.5+재설치0.8' },
    { id: 'cab-rebuild',     name: '전체 해체 재설치', unit: '품/개소', value: 1.5, note: '목공' },
    { id: 'cab-door',        name: '문짝 교체',       unit: '품/개소', value: 0.5, note: '목공' },
    { id: 'cab-hinge',       name: '경첩·레일 교체',  unit: '품/개소', value: 0.3, note: '목공' },
    // 싱크대 (표준품셈 7장 설비공사 + 5장 수장공사)
    { id: 'sink-remove',     name: '싱크대 철거',       unit: '품/m',  value: 0.2, note: '설비공' },
    { id: 'sink-remove-gen', name: '싱크대 철거 보조',   unit: '품/m',  value: 0.2, note: '보통인부' },
    { id: 'sink-lower-inst', name: '하부장 설치',       unit: '품/m',  value: 0.25, note: '목공' },
    { id: 'sink-upper-inst', name: '상부장 설치',       unit: '품/m',  value: 0.15, note: '목공' },
    { id: 'sink-deco-inst',  name: '장식장 설치',       unit: '품/m',  value: 0.2,  note: '목공 · 색상통일 교체' },
    { id: 'sink-top-inst',   name: '상판 설치',        unit: '품/m',  value: 0.15, note: '석재공/목공' },
    { id: 'sink-faucet-inst', name: '수전 설치',        unit: '품/대', value: 0.2, note: '설비공' },
    { id: 'sink-supply',     name: '급수 배관 연결',    unit: '품/식', value: 0.3, note: '설비공 · 냉온수' },
    { id: 'sink-drain',      name: '배수 배관 연결',    unit: '품/식', value: 0.2, note: '설비공 · 트랩+연결' },
    { id: 'sink-pipe-remove', name: '배관 철거',        unit: '품/식', value: 0.3, note: '설비공' },
    { id: 'sink-caulk',      name: '코킹 마감',        unit: '품/식', value: 0.1, note: '설비공' },
    { id: 'sink-test',       name: '누수 테스트',       unit: '품/회', value: 0.1, note: '설비공' },
    { id: 'sink-tile-remove', name: '타일 철거 (벽면)',  unit: '품/㎡', value: 0.15, note: '타일공' },
    { id: 'sink-tile-inst',   name: '타일 시공 (벽면)',  unit: '품/㎡', value: 0.2,  note: '타일공' },
    // 바닥 (표준품셈 5장 수장공사)
    { id: 'fl-gang-inst',   name: '강마루 시공',     unit: '㎡/일', value: 20,   note: '마루공 1인' },
    { id: 'fl-ondol-inst',  name: '온돌마루 시공',   unit: '㎡/일', value: 15,   note: '마루공 1인' },
    { id: 'fl-jang-inst',   name: '장판 시공',       unit: '㎡/일', value: 40,   note: '장판공 1인' },
    { id: 'fl-tile-inst',   name: '바닥 타일 시공',  unit: '㎡/일', value: 8,    note: '타일공 1인' },
    { id: 'fl-remove-gang', name: '강마루 철거',     unit: '품/㎡', value: 0.02, note: '보통인부' },
    { id: 'fl-remove-ondol', name: '온돌마루 철거',  unit: '품/㎡', value: 0.03, note: '보통인부' },
    { id: 'fl-remove-jang', name: '장판 철거',       unit: '품/㎡', value: 0.01, note: '보통인부' },
    { id: 'fl-sanding',     name: '바닥 샌딩',       unit: '품/㎡', value: 0.02, note: '보통인부+장비' },
    { id: 'fl-leveling',    name: '레벨링 시공',     unit: '품/㎡', value: 0.03, note: '미장공' },
    // 페인트 (표준품셈 6장 도장공사)
    { id: 'pt-wall-inst',   name: '벽면 도장 (2회)', unit: '㎡/일', value: 40,   note: '도장공 1인' },
    { id: 'pt-ceil-inst',   name: '천장 도장 (2회)', unit: '㎡/일', value: 30,   note: '도장공 1인' },
    { id: 'pt-remove',      name: '기존 도막 제거',  unit: '품/㎡', value: 0.015, note: '도장공' },
    { id: 'pt-putty-work',  name: '퍼티 작업',       unit: '품/㎡', value: 0.01, note: '도장공' },
    { id: 'pt-primer-work', name: '프라이머 도포',   unit: '품/㎡', value: 0.008, note: '도장공' },
    { id: 'pt-usage',       name: '페인트 소요량',   unit: 'L/㎡',  value: 0.15, note: '2회 도포 기준' },
    // 화장실 (표준품셈 4장 타일 + 7장 설비 + 방수)
    { id: 'bt-tile-fl-inst', name: '바닥타일 시공',  unit: '품/㎡', value: 0.25, note: '타일공' },
    { id: 'bt-tile-wall-inst', name: '벽타일 시공',  unit: '품/㎡', value: 0.2,  note: '타일공' },
    { id: 'bt-tile-fl-rmv', name: '바닥타일 철거',   unit: '품/㎡', value: 0.15, note: '보통인부+장비' },
    { id: 'bt-tile-wall-rmv', name: '벽타일 철거',   unit: '품/㎡', value: 0.12, note: '보통인부+장비' },
    { id: 'bt-waterproof-inst', name: '바닥 방수',   unit: '품/㎡', value: 0.2,  note: '방수공 · 2회+보호몰탈' },
    { id: 'bt-grout-work',  name: '줄눈 시공',       unit: '품/㎡', value: 0.05, note: '타일공' },
    { id: 'bt-toilet-rmv',  name: '양변기 철거',     unit: '품/대', value: 0.3,  note: '설비공' },
    { id: 'bt-toilet-inst', name: '양변기 설치',     unit: '품/대', value: 0.3,  note: '설비공' },
    { id: 'bt-basin-rmv',   name: '세면대 철거',     unit: '품/대', value: 0.2,  note: '설비공' },
    { id: 'bt-basin-inst',  name: '세면대 설치',     unit: '품/대', value: 0.3,  note: '설비공' },
    { id: 'bt-dome-rmv',    name: '돔천장 철거',     unit: '품/식', value: 0.3,  note: '보통인부' },
    { id: 'bt-dome-inst',   name: '돔천장 설치',     unit: '품/식', value: 0.3,  note: '보통인부' },
    { id: 'bt-damsu',       name: '담수 테스트',     unit: '품/회', value: 0.3,  note: '설비공 · 48시간' },
    // 도배 프라이머 (누수 피해 세대 필수)
    { id: 'dobae-primer',    name: '벽면 프라이머 도포', unit: '품/㎡', value: 0.005, note: '도배공 · 누수 하지처리' },
    { id: 'dobae-primer-use', name: '프라이머 소요량',   unit: 'L/㎡',  value: 0.1,   note: '1회 도포 기준' },
    // 현장 조건 품셈
    { id: 'dust-barrier',    name: '분진 차단막 설치', unit: '품/회',  value: 0.3,  note: '보통인부' },
    { id: 'mold-treat-work', name: '곰팡이 방지 도포', unit: '품/㎡',  value: 0.008, note: '보통인부' },
    { id: 'light-remove',    name: '조명 분리',       unit: '품/개소', value: 0.3,  note: '전기공' },
    { id: 'light-install',   name: '조명 재설치',     unit: '품/개소', value: 0.3,  note: '전기공' },
    { id: 'caulk-work',      name: '코킹 마감',      unit: '품/m',   value: 0.02, note: '목공' },
    { id: 'dry-check',       name: '하지 건조 확인',   unit: '품/회',  value: 0.5,  note: '보통인부 · 수분측정' },
  ],

  // 이사·숙박 단가
  moving: [
    { id: 'mv-pack',      name: '포장 인부',          unit: '인/일', price: 150316, source: '시중노임단가 · 보통인부' },
    { id: 'mv-truck-1t',   name: '운반 차량 (1톤)',    unit: '회',   price: 150000, source: '시장가' },
    { id: 'mv-truck-25t',  name: '운반 차량 (2.5톤)',  unit: '회',   price: 250000, source: '시장가' },
    { id: 'mv-truck-5t',   name: '운반 차량 (5톤)',    unit: '회',   price: 400000, source: '시장가' },
    { id: 'mv-container',  name: '컨테이너 보관',      unit: '일',   price: 5000,   source: '시장가 · 20ft 기준' },
    { id: 'mv-warehouse',  name: '창고 보관',          unit: '일',   price: 8000,   source: '시장가 · 3평 기준' },
    { id: 'mv-hotel',      name: '숙박 (비즈니스호텔)', unit: '박',   price: 80000,  source: '시장가 · 2인 기준' },
    { id: 'mv-motel',      name: '숙박 (모텔)',        unit: '박',   price: 50000,  source: '시장가 · 2인 기준' },
    { id: 'mv-packing',    name: '포장 자재 (박스·에어캡)', unit: '식', price: 50000, source: '시장가' },
  ],

  // 기타 단가
  etc: [
    { id: 'waste-sticker',   name: '폐기물 스티커', unit: '장', price: 30000,  note: '' },
    { id: 'waste-transport',  name: '폐기물 운반',  unit: '회', price: 60000,  note: '1톤 트럭' },
    { id: 'mold-chemical',   name: '곰팡이 약품',  unit: '식', price: 100000, note: '' },
    { id: 'insulation-mat',  name: '단열재',       unit: '㎡', price: 15000,  note: '물가정보' },
  ]
};
